source 'https://rubygems.org'

gem 'middleman', '~> 3.3.12'
gem 'middleman-blog', '~> 3.5.3'
gem 'middleman-syntax'
gem 'middleman-deploy'
gem 'middleman-title'
gem 'middleman-meta-tags'
gem 'middleman-search_engine_sitemap'
gem 'middleman-minify-html'
gem 'middleman-livereload'
gem 'middleman-sprockets'
gem 'rack-contrib'
gem 'rack-rewrite'
gem 'slim'
gem 'nokogiri', '1.6.7'
gem 'middleman-autoprefixer'
gem 'sass-media_query_combiner'
gem 'redcarpet'
gem 'rake'
gem 'builder', '~> 3.0'
gem 'bourbon', '~> 4.2', '>= 4.2.6'
gem 'sass', '~> 3.4', :require => false
gem 'middleman-alias'
